package model.pojo;
// Generated 23.05.2017 18:25:49 by Hibernate Tools 4.3.1



/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String city;
     private String country;
     private Integer rating;
     private String imgUrl;

    public Hotel() {
    }

    public Hotel(String name, String city, String country, Integer rating, String imgUrl) {
       this.name = name;
       this.city = city;
       this.country = country;
       this.rating = rating;
       this.imgUrl = imgUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }




}


